### ISSUE TITLE
undefined popup message when checkout and opting to create a new account

### ISSUE THREAD

**Issue by ProxiBlue** [afterpay/afterpay-magento#10]
hi,

We are getting errors in checkout when a customer creates a new account in checkout.
This is not a GUEST checkout, which is disabled in our store.
The end result is a js popup which note just 'undefined' and then checkout is hung.

I had a quick look and I can see the issue comes from 

https://github.com/afterpay/afterpay-magento/blob/master/src/js/Afterpay/checkout/onepage.js
the response from the URL call is not correctly trapped, and the actual error is lost to the display.

Looking at the response from the  call I get this:

![selection_377](https://cloud.githubusercontent.com/assets/4994260/21305068/568217b2-c604-11e6-96ab-79f4c7e4aa6b.png)

Is this a known issue?
Is there an issue with new accounts and checkout using afterpay

The url being called, that ends up on a login page:

http://www.example.com/afterpay/payment/start/form_key/zevgFkk7IMAKJ7LD/

**Comment by stevenocta** [comment]
The Gateway Error is most likely a credentials issue.
If you have the logging turned on, you might see error 401 - Incorrect Credentials in the logs

**Comment by ProxiBlue** [comment]
Hi.

What credentials are you refering to? Customer or afterpay admin for api?

**Comment by ProxiBlue** [comment]
Works fine if you first create a customer account, then proceed to checkout logged in.

The issue arrise if you opt to create an account at checkout. 

Not sure what credentials you are refering to.

**Comment by ProxiBlue** [comment]
Ok, so looking into this now, I find that at start of checkout, magento is correctly setting the method to 'register'

![image](https://cloud.githubusercontent.com/assets/4994260/21668344/e3d44d1c-d33b-11e6-9d55-3d2522a6f2db.png)

but when Afterpay controller reads the quote object, it gets back 'guest' as the checkout method.

So, the issue is then, why is that happening.
second issue here is trapping the error in the afterpay .js correctly so there is not just 'undefined'

**Comment by ProxiBlue** [comment]
https://github.com/afterpay/afterpay-magento/blob/master/src/app/code/community/Afterpay/Afterpay/controllers/PaymentController.php#L899

that is resetting checkout back to GUEST

**Comment by ProxiBlue** [comment]
@stevenocta - any reason this was closed, without further information?
