### ISSUE TITLE
images delivered over http:

### ISSUE THREAD

**Issue by sholdowa** [afterpay/afterpay-magento#13]
this is causing problems with the checkout. Is this a configuration issue, or on your side?

**Comment by stevenocta** [comment]
Hi,

Thank you for your asset delivery query.

At current, the Afterpay display and marketing assets are delivered over http. The delivery method is managed by the Afterpay marketing department.

The possibility of delivering the assets over https has been raised with the team for their consideration.

Thank you

**Comment by WesMage** [comment]
Can we leave this open until it resolved? 
This sounds like a pretty serious issue

**Comment by sholdowa** [comment]
You're joking, right?
 - a free letsencrypt cert
 - a trivial config change
 - just always deliver via https:
And you're providing an useable product.

Google almost demand that sites are delivered via https: these days. We can't live with sites broken by your software.
