### ISSUE TITLE
Afterypay not working after reinstalling.

### ISSUE THREAD

**Issue by kimrheen18** [afterpay/afterpay-magento#15]
Hi Good day!

My afterpay module is not working after I reinstalled/re-upload the file on the code directory. I can configure the Afterpay on the the Magento Configruation, but on the frontend, specially on the cart, afterpay does not display there.

What is the problem of this?
I need your help guys. 

TIA!

**Comment by stevenocta** [comment]
Hi,

Thank you for your Afterpay front-end display query.

The item you've raised relates to a site-specific Afterpay integration, rather than that of a particular Afterpay-Magento plugin version.

Please liaise with your Afterpay Account Manager for assistance with your integration.

Thank you.
