### ISSUE TITLE
No installments are shown

### ISSUE THREAD

**Issue by adarshkhatri** [afterpay/afterpay-magento#16]
I can confirm they were showing before.

I have updated the extension with latest version as of today and no installments are displayed in product/category/checkout pages.

I have allowed to show all these from admin area.

Everything else is working, haven't tested for order though.

Magento v. 1.13.1.0

Anything I am missing?

**Comment by stevenocta** [comment]
Hi Adarsh,

Thank you for your installment display query.

The item you've raised relates to a site-specific Afterpay integration, rather than that of a particular Afterpay-Magento plugin version.

Please liaise with your Afterpay Account Manager for assistance with your integration.

Thank you.
