### ISSUE TITLE
Issue with running afterpay_setup

### ISSUE THREAD

**Issue by thoughtyards** [afterpay/afterpay-magento#6]
What I noticed is with the version availbale on the GIT you couldn't achieve the full working afterpay.  Its a disaster.

What I see is 
       <Afterpay_Afterpay>
            <version>0.13.0</version>
        </Afterpay_Afterpay>

leaves us with only entry for two columns afterpay_token, afterpay_order_id in the table sales_flat_quote_payment.  Whereby we need the full fledged sql scripts included in all of setups to make after pay works seamlessly.

My live site went in to issue cause core_resources have entry for afterpay which shows I am on 0.13.0 which is lates and anticipated all backwards version were executed.

It lead me the lot's of error on cron's and my orders no more synced with after pay i don't have reference with afterpay order Id's in the database ( since columns not created on my order tables ).

I was wondering why this has happened. may be after pay consider to put the correct version and proper updates on the sql version control.

what work around i did is i consolidated all sql installation script into one file and ran the updates.

now it's working fine and my cron are back to normals .

But It was big dent on the trust how module works.

**Comment by stevenocta** [comment]
Hi, 
We have made changes on the install script around 1 or 2 weeks ago based on the feedbacks on the SQL installation scripts.

https://github.com/afterpay/afterpay-magento/pull/5/files

The changes have been deployed 28 days ago. 
Have you downloaded the updated extension after the updates have been made?

**Comment by thoughtyards** [comment]
We have downloaded the module even before 28th October

**Comment by stevenocta** [comment]
The issue should be fixed in the newest version.
Also, we will remove the try-catch block on the SQL so Magento can trap the error correctly in setup.

**Comment by thoughtyards** [comment]
Okay great .. I will update the version
