### ISSUE TITLE
Please sort out your modules install / versioning. 

### ISSUE THREAD

**Issue by ProxiBlue** [afterpay/afterpay-magento#9]
Hi,

Afterpay is making it very difficult to use your module, and to allow for upgrades.
As it stands we have to effect downtime to just update the previous installed module, as your module versioning is really broken.

So lets first start with the facts as noted here:  https://github.com/afterpay/afterpay-magento/issues/6 and here: https://github.com/afterpay/afterpay-magento/pull/5

The modules install was just not working, and plenty of tables/fields were not created. I discussed this with your team via direct emails as well.

Ok, so now you guys have produced an update, and moved your versioning to  0.13.1 - which is a good move. ( https://github.com/afterpay/afterpay-magento/blob/master/src/app/code/community/Afterpay/Afterpay/etc/config.xml ) BUT you have again missed the point in the versioning:

Your latest module version file is: 0.13.0 (https://github.com/afterpay/afterpay-magento/tree/master/src/app/code/community/Afterpay/Afterpay/sql/afterpay_setup) **BUT that was the exact same version you had previously distributed.**

It does not help that you have edited that last setup script and placed all the 'lost' setup directives into it - WE ALREADY RAN 0.13.0 (as per previous setup) - so that is now what our magento install is on. Having that setup script now as the 'most recent' will simply not work.

You should create a new setup file, versioned to 0.13.1.php, and THAT should have the updates. It does not help us if you keep at the same version as what we have installed. To fix this, we will need to place our site in maintenance mode, edit db, change versions of 'what magento thinks is installed' deploy new version, get 'what is existing version to re-run' and then place our site back in live mode.

Frankly, having to place a site in maintenance mode to fix this is simply not acceptable, and can be solved if you guys just sort out your modules installs properly.

If you guys are unsure what to do, ask. There is a community available to help.

PLEASE! This is getting ridiculous now.

**Comment by ProxiBlue** [comment]
Also, if you are going to collapse all your previous upgrade scripts to the most recent version, please also take the effort to delete all the old/previous setup/upgrade scripts.
Having them there can cause wasted time by us developers having to look at WTF is going on, as they are misleading now. They are not used. Easy to miss the fact that there is a later 'install-xx.xx.xx.php' version in the folder as well.

**Comment by stevenocta** [comment]
All the redundant ones should have been deleted by now. 
The remaining update scripts (e.g. 0.12.9 to 0.13.0) would be needed for the merchants who are updating from an older version of the plugin.

**Comment by ProxiBlue** [comment]
Ok, thanks, that will help.

To overcome the upgrade and install of the module (since your people had supplied us a broken 0.13.0 module not more than a week/2 weeks ago) - I installed this github version, but I copied the install.0.13.0.php to install-0.13.1 (matching the latest version number) - to allow it to run

This then allowed me to deploy without having to take site down, and muck about in db to change version numbers in core_resource, but now my local version is not the same :( - but at least our site did not need to be taken down.

Hope to see this versioning and install sorted in yoru next release. All in all the module works fine, it is just the install that has been a pain.

**Comment by ProxiBlue** [comment]
@stevenocta  - another issue: the fact that you are placing try catch blocks around the module install code.

In this example: https://github.com/afterpay/afterpay-magento/blob/master/src/app/code/community/Afterpay/Afterpay/sql/afterpay_setup/install-0.13.0.php#L17 The module installed, but some install issue with tables did not action the install, and the error was silently trapped, and lost. So, it *looks* like the module installed, but it did not (again)

If that try catch is dropped, magento install will trap the issue, and report it, preventing the module to install, and preventing versioning to increase, causing more issues going forward - not being able to re-install.

Please release a new version and remove the catch block, unless you have a valid reason that I cannot figure out. Please do share so i can understand. 

(still don;t know why, as the reason is lost due to code)

**Comment by stevenocta** [comment]
@ProxiBlue : 
We will review the try-catch codes and decide whether we will removethe try-catch structure. 
Another possibility is to log the install error in the system, so that we can see if there is any install errors.

Thank you for the suggestion.
